import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  safe: { flex: 1, paddingHorizontal: 22 },
  close: {
    alignSelf: "flex-end",
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryFaint,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 6,
  },
  sparkles: {
    position: "absolute",
    top: "15%",
    left: 36,
    right: 36,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  photos: {
    width: 250,
    height: 150,
    marginBottom: 28,
  },
  photoRing: {
    position: "absolute",
    width: 132,
    height: 132,
    borderRadius: 66,
    padding: 5,
    borderWidth: 2,
    borderColor: colors.accent,
    backgroundColor: colors.bg,
  },
  ownRing: { left: 4, top: 8, transform: [{ rotate: "-5deg" }] },
  targetRing: { right: 4, top: 8, transform: [{ rotate: "5deg" }] },
  photo: {
    width: "100%",
    height: "100%",
    borderRadius: 60,
  },
  placeholder: {
    backgroundColor: colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
  },
  initial: {
    color: colors.accent,
    fontSize: 42,
    fontWeight: "800",
  },
  linkIcon: {
    position: "absolute",
    left: 107,
    top: 57,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
    borderWidth: 3,
    borderColor: colors.bg,
    zIndex: 5,
  },
  eyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  title: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 8,
  },
  copy: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    marginTop: 10,
    maxWidth: 330,
  },
  sharedCard: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    backgroundColor: colors.primaryFaint,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    borderRadius: 16,
    padding: 14,
    marginTop: 26,
  },
  sharedCopy: { marginLeft: 12, flex: 1 },
  sharedTitle: { color: colors.text, fontSize: 14, fontWeight: "700" },
  sharedText: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
  actions: { paddingBottom: 12 },
  chatButton: {
    height: 56,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: colors.accent,
  },
  chatButtonText: {
    color: colors.accentDark,
    fontSize: 16,
    fontWeight: "800",
  },
  laterButton: {
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  laterText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: "700",
  },
});
